### ISSUE TITLE
Container conflict when running action inside ubuntu:18.04

### ISSUE THREAD

**Issue by josejich** [philips-software/sonar-scanner-action#112]
Currently running this action inside a ubuntu 18.04 or a ubuntu 20.04 container has a conflict which prevents the repository to be properly identified as a github repository. To reproduce this issue here is a simple example; consider the following yml file that includes this action, running in the container **python:3.9**:

>     jobs:
>     build:
>         runs-on: [self-hosted, research]
>         container: python:3.9
> 
>         steps:
>             - name: Checkout
>             uses: actions/checkout@v2
> 
>         - name: Sonar analysis configuration      
>             uses: philips-software/sonar-scanner-action@v1.3.0
>             with:
>             token: ${{ secrets.SONARQUBE_TOKEN }}
>             projectName: <projectName>
>             projectKey: <projectKey>
>             url: <sonarqube-server-url>

If you try to run this simplified action in a given C++ Cmake based repository you will get the following failure log:

```
2021-11-26T13:50:57.0503295Z INFO: ------------------------------------------------------------------------
2021-11-26T13:50:57.0504376Z INFO: EXECUTION FAILURE
2021-11-26T13:50:57.0505626Z INFO: ------------------------------------------------------------------------
2021-11-26T13:50:57.0506152Z INFO: Total time: 1:04.786s
2021-11-26T13:50:57.3103531Z INFO: Final Memory: 98M/337M
2021-11-26T13:50:57.3105121Z INFO: ------------------------------------------------------------------------
2021-11-26T13:50:57.3111631Z ERROR: Error during SonarScanner execution
2021-11-26T13:50:57.3119804Z java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /build-wrapper-dump.json
2021-11-26T13:50:57.3123164Z 	at com.sonar.cpp.plugin.BuildWrapperJsonReader.readCaptures(BuildWrapperJsonReader.java:90)
2021-11-26T13:50:57.3126348Z 	at com.sonar.cpp.plugin.CFamilySensor.process(CFamilySensor.java:575)
```
Which is the expected; since the project has yet to be build and the output of the build-wrapper tool is missing. However, if you change the container to a **ubuntu:18.04** or **ubuntu:20.04**  :

>     jobs:
>     build:
>         runs-on: [self-hosted, research]
>         container: ubuntu:18.04
> 
>         steps:
>             - name: Checkout
>             uses: actions/checkout@v2
> 
>         - name: Sonar analysis configuration      
>             uses: philips-software/sonar-scanner-action@v1.3.0
>             with:
>             token: ${{ secrets.SONARQUBE_TOKEN }}
>             projectName: <projectName>
>             projectKey: <projectKey>
>             url: <sonarqube-server-url>

It fails as follows:

```
2021-11-26T14:02:01.2433137Z INFO: Project configuration:
2021-11-26T14:02:01.2473405Z INFO:   Excluded sources: **/*Test*/**, **/*Tests*/**
2021-11-26T14:02:01.2694317Z INFO: ------------------------------------------------------------------------
2021-11-26T14:02:01.2695221Z INFO: EXECUTION FAILURE
2021-11-26T14:02:01.2696269Z INFO: ------------------------------------------------------------------------
2021-11-26T14:02:01.2697011Z INFO: Total time: 13.658s
2021-11-26T14:02:01.3105547Z INFO: Final Memory: 7M/30M
2021-11-26T14:02:01.3107046Z INFO: ------------------------------------------------------------------------
2021-11-26T14:02:01.3122217Z ERROR: Error during SonarScanner execution
2021-11-26T14:02:01.3123127Z ERROR: Not inside a Git work tree: /github/workspace
```
It complains of not being inside a repository, which is not the expected behavior.

**Comment by josejich** [comment]
Turns out this was an issue of my own making, apparently the **Checkout** action requires a version of git above 1.8. This requirement is fulfilled in the python container, but on Ubuntu 18.04 the version available is 1.7.x (so its not worth it to try to apt-get install on that container) causing a failure. A newer version of git is available on the Ubuntu 20.04 container but then this must be installed before trying to run the checkout action. As a workaroud in the Ubuntu-18.04 container can be achieve by compiling a newer version of git from source code:

          apt-get install libz-dev zip -y
          apt-get install curl -y
          apt-get install libcurl4-openssl-dev -y
          apt-get install gettext -y
          curl https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.32.0.tar.gz --output /opt/git-2.32.0.tar.gz
          tar -zxf /opt/git-2.32.0.tar.gz -C /opt/
          cd /opt/git-2.32.0
          ./configure  NO_TCLTK=true --prefix=/usr/local
          make all
          make install
          git --version
