### ISSUE TITLE
UnsupportedClassVersionError when running sonarqube action

### ISSUE THREAD

**Issue by tom-brosch** [philips-software/sonar-scanner-action#90]
We are in the process of migrating OmniLearn from Gitlab to Github. We tried to use the sonarqube action to activate sonarqube analysis of our project. We did this by adding the following snippet to our Github workflow configuration

```
- name: Update sonarqube
  uses: philips-software/sonar-scanner-action@v1.2.0
  with:
      token: ${{ secrets.SONARQUBE_TOKEN }}
      projectName: omnilearn
      projectKey: prh.omnilearn-linux
      url: https://sonarqube.ta.philips.com/
```
When running the workflow, we currently get the following error:
```
/root/sonar-scanner-4.3.0.2102-linux/bin/sonar-scanner -Dsonar.login=*** -Dsonar.host.url=https://sonarqube.ta.philips.com/ -Dsonar.projectKey=prh.omnilearn-linux -Dsonar.projectName='omnilearn' -Dsonar.scm.provider=git -Dsonar.sourceEncoding=UTF-8 -Dsonar.qualitygate.wait=false -Dsonar.branch.name=develop
  INFO: Scanner configuration file: /root/sonar-scanner-4.3.0.2102-linux/conf/sonar-scanner.properties
  INFO: Project root configuration file: /github/workspace/sonar-project.properties
  INFO: SonarScanner 4.3.0.2102
  INFO: Java 1.8.0_252 Oracle Corporation (64-bit)
  INFO: Linux 4.14.243-185.433.amzn2.x86_64 amd64
  INFO: User cache: /root/.sonar/cache
  INFO: Scanner configuration file: /root/sonar-scanner-4.3.0.2102-linux/conf/sonar-scanner.properties
  INFO: Project root configuration file: /github/workspace/sonar-project.properties
  INFO: Analyzing on SonarQube server 9.0.1
  INFO: Default locale: "en_US", source code encoding: "UTF-8"
  INFO: ------------------------------------------------------------------------
  INFO: EXECUTION FAILURE
  INFO: ------------------------------------------------------------------------
  INFO: Total time: 1.666s
  INFO: Final Memory: 4M/72M
  INFO: ------------------------------------------------------------------------
  ERROR: Error during SonarScanner execution
  java.lang.UnsupportedClassVersionError: org/sonar/batch/bootstrapper/EnvironmentInformation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  	at java.lang.ClassLoader.defineClass1(Native Method)
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.createBatch(DefaultBatchFactory.java:32)
  	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
  	at com.sun.proxy.$Proxy0.execute(Unknown Source)
  	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
  	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
  	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
  	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
  	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
  ERROR: 
  ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
  Error: The process '/root/sonar-scanner-4.3.0.2102-linux/bin/sonar-scanner' failed with exit code 1
```
I don't quite understand what the error is and how to fix it. Can you please help with this?

**Comment by tom-brosch** [comment]
Switch to 1.3.0, which doesn't produce this error.
